### ISSUE TITLE
Unable to open a file

### ISSUE THREAD

**Issue by svenkost** [anboralabs/intellij-jmeter#5]
When clicking a jmx file located in /src/test/jmeter, I get this error: 

java.lang.IllegalArgumentException: Problem loading XML from:'/Users/myuser/source/myproject/src/test/jmeter/script.jmx'. 
Cause:
CannotResolveClassException: jmeterTestPlan

 Detail:com.thoughtworks.xstream.mapper.CannotResolveClassException: jmeterTestPlan

**Comment by dalgarins** [comment]
@svenkost could you share your jmx file?

**Comment by IncredibleLou** [comment]
@dalgarins  same here. 
I used JMeter 5.6.2 to create a very simple .jmx file. 

``` 
<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.2">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Test Plan" enabled="true">
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.tearDown_on_shutdown">false</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
    </TestPlan>
    <hashTree>
      <SetupThreadGroup guiclass="SetupThreadGroupGui" testclass="SetupThreadGroup" testname="setUp Thread Group" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
          <stringProp name="LoopController.loops">1</stringProp>
          <boolProp name="LoopController.continue_forever">false</boolProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">1</stringProp>
        <stringProp name="ThreadGroup.ramp_time">1</stringProp>
        <boolProp name="ThreadGroup.scheduler">false</boolProp>
        <stringProp name="ThreadGroup.duration"></stringProp>
        <stringProp name="ThreadGroup.delay"></stringProp>
        <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
      </SetupThreadGroup>
      <hashTree/>
    </hashTree>
  </hashTree>
</jmeterTestPlan>
```

Opening it results in the following error: 

```
java.lang.IllegalArgumentException: Problem loading XML from:[..]\test.jmx'. 
Cause:
CannotResolveClassException: jmeterTestPlan

 Detail:com.thoughtworks.xstream.mapper.CannotResolveClassException: jmeterTestPlan
```

**Comment by dalgarins** [comment]
@IncredibleLou could you share your plugin configuration? because I have created the same file that share and I'm able to open.
<img width="1015" alt="Screenshot 2023-11-05 at 5 54 54 PM" src="https://github.com/anboralabs/intellij-jmeter/assets/8527174/477fddef-ee08-487b-8af2-8c10390393e8">

<img width="1015" alt="Screenshot 2023-11-05 at 5 54 35 PM" src="https://github.com/anboralabs/intellij-jmeter/assets/8527174/f6a70ef3-ba47-4e53-9a3b-2e1097e76bfe">

<img width="973" alt="Screenshot 2023-11-05 at 5 56 33 PM" src="https://github.com/anboralabs/intellij-jmeter/assets/8527174/8319f84a-31f4-4022-9bec-0b5e672bebd5">

**Comment by dalgarins** [comment]
@svenkost and @IncredibleLou did the configuration fix your issue?

**Comment by IncredibleLou** [comment]
@dalgarins I checked the configuration and as far as I see it I use the same as you. 
![image](https://github.com/anboralabs/intellij-jmeter/assets/23636564/f4489bc6-72d9-4aa8-b3d9-7e48df579e47)

I have my own JMeter installation on the user PATH. Could this be an issue?

**Comment by rabestro** [comment]
> @svenkost and @IncredibleLou did the configuration fix your issue?

Same issue on my machine. I used the plugin successfully several months ago. Today I needed to open the Jmeter file and I have got the error.

**Comment by dalgarins** [comment]
@rabestro could you share your jmeter file?

**Comment by rabestro** [comment]
<img width="700" alt="image" src="https://github.com/anboralabs/intellij-jmeter/assets/52966251/91340249-d05a-4c1d-81cb-d5de56f55ed5">

**Comment by rabestro** [comment]
@dalgarins we have a problem with the last version of this dependency in our project: `com.thoughtworks.xstream:xstream:1.4.20`. It seems that it can be the reason for the error.

**Comment by dalgarins** [comment]
@rabestro do you have plugins installed? which one do you have? I opened the file and works for me, but maybe the issue is related with a custom plugin, I would like to validate that.

<img width="966" alt="Screenshot 2024-01-04 at 6 36 31 AM" src="https://github.com/anboralabs/intellij-jmeter/assets/8527174/efba0602-2220-4c64-804b-b9de506452fc">

**Comment by rabestro** [comment]
> @rabestro do you have plugins installed? which one do you have? I opened the file and works for me, but maybe the issue is related with a custom plugin, I would like to validate that.

<img width="610" alt="image" src="https://github.com/anboralabs/intellij-jmeter/assets/52966251/d571f2b5-f133-4a5c-b2be-03eec0b646f7">

**Comment by dalgarins** [comment]
@rabestro why in the back is the jmeter version? the new version of the plugin has his own plugin repository, please in the tools menu click on jmeter plugin manager, and share with me the plugins you have, but in that specific option. not your custom jmeter installation.

thanks

**Comment by rabestro** [comment]
```
PS /Users/jegors/Projects/engx-advanced/pig-latin-rest/jmeter-test> jmeter -v
WARNING: package sun.awt.X11 not in java.desktop
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
    _    ____   _    ____ _   _ _____       _ __  __ _____ _____ _____ ____
   / \  |  _ \ / \  / ___| | | | ____|     | |  \/  | ____|_   _| ____|  _ \
  / _ \ | |_) / _ \| |   | |_| |  _|    _  | | |\/| |  _|   | | |  _| | |_) |
 / ___ \|  __/ ___ \ |___|  _  | |___  | |_| | |  | | |___  | | | |___|  _ <
/_/   \_\_| /_/   \_\____|_| |_|_____|  \___/|_|  |_|_____| |_| |_____|_| \_\ 5.6.2

Copyright (c) 1999-2023 The Apache Software Foundation

PS /Users/jegors/Projects/engx-advanced/pig-latin-rest/jmeter-test> jmeter
```

<img width="710" alt="image" src="https://github.com/anboralabs/intellij-jmeter/assets/52966251/2927acbd-d464-4c2a-a871-2022394c8007">

<img width="677" alt="image" src="https://github.com/anboralabs/intellij-jmeter/assets/52966251/3951d59e-4099-4f75-b928-ec0b2b8db1fc">

<img width="847" alt="image" src="https://github.com/anboralabs/intellij-jmeter/assets/52966251/e5af3bc4-6ff4-41fa-ab63-e1777c1319b9">

<img width="677" alt="image" src="https://github.com/anboralabs/intellij-jmeter/assets/52966251/78126509-7dc3-4b07-9785-f66cb473839f">

<img width="962" alt="image" src="https://github.com/anboralabs/intellij-jmeter/assets/52966251/91b7f99a-49d5-4c56-9805-ec3f7640e108">

GitHub repo: https://github.com/rabestro/pig-latin-rest

**Comment by dalgarins** [comment]
@rabestro inside the IDE intellij in the tools menu.

<img width="1330" alt="Screenshot 2024-01-08 at 7 01 27 AM" src="https://github.com/anboralabs/intellij-jmeter/assets/8527174/e262a9b7-6af4-433d-9950-b747c4498fac">

<img width="1330" alt="Screenshot 2024-01-08 at 7 01 40 AM" src="https://github.com/anboralabs/intellij-jmeter/assets/8527174/8272a920-3602-4413-a764-3d4e1aadf6fe">

the plugin jmeter for intellij has his own plugin repository inside the IDE, don't open the standalone jmeter application.

**Comment by rabestro** [comment]
<img width="1512" alt="image" src="https://github.com/anboralabs/intellij-jmeter/assets/52966251/3cf1d824-c463-4d12-b667-bfaef56be970">

**Comment by dalgarins** [comment]
@rabestro do you see in the images? in your standalone jmeter you have some plugins installed, install the same plugins in the IDE plugin for jmeter, for example 3 Basic graphs is not installed in the jmeter plugin inside the IDE. please installs them and let me know if that fixed your issue.

**Comment by dalgarins** [comment]
@rabestro let me check something you have your jmeter standalone application in the path? I mean, you can execute your jmeter from your shell on your machine? it's because I think I have a similar issue reported.

**Comment by rabestro** [comment]
> @rabestro let me check something you have your jmeter standalone application in the user path?

Yes

**Comment by dalgarins** [comment]
@rabestro I would like to validate something, the issue started after update the plugin or you installed the plugin for first time on a new IDE of you and you are having that issue?

**Comment by dalgarins** [comment]
@rabestro also could you copy the whole error message in the dialog?

**Comment by dalgarins** [comment]
@rabestro I think I have found the issue, I need a little help, please open the jmeter repository of the plugin and select jmeter core, when you select it will show you a path in the description that path is the plugin path inside the IDE, please go to that path and check if bin folder exists also send a list of all files inside that folder. thank you.

**Comment by rabestro** [comment]
> @rabestro also could you copy the whole error message in the dialog? I mean, when you open the jmeter file and the error is showed could you copy here the message?

```
java.lang.IllegalArgumentException: Problem loading XML from:'/Users/jegors/Projects/engx-advanced/pig-latin-rest/jmeter-test/SmokeTest.jmx'. 
Cause:
CannotResolveClassException: jmeterTestPlan

 Detail:com.thoughtworks.xstream.mapper.CannotResolveClassException: jmeterTestPlan
```

**Comment by rabestro** [comment]
> @rabestro I think I have found the issue, I need a little help, please open the jmeter repository of the plugin and select jmeter core, when you select it will show you a path in the description that path is the plugin path inside the IDE, please go to that path and check if bin folder exists also send a list of all files inside that folder. thank you.

Location: /Users/jegors/Library/Application Support/JetBrains/IntelliJIdea2023.3/plugins/jmeter-intellij/lib/instrumented-jmeter-intellij-1.2.3.jar
 
<img width="1024" alt="image" src="https://github.com/anboralabs/intellij-jmeter/assets/52966251/c6a47b8b-4b1f-444b-9e4b-24221da9e87a">

<img width="263" alt="image" src="https://github.com/anboralabs/intellij-jmeter/assets/52966251/150bcf22-4483-4339-aae7-f7726a547421">
```shell
PS /Users/jegors/Library/Application Support/JetBrains/IntelliJIdea2023.3/plugins/jmeter-intellij> ls
lib
PS /Users/jegors/Library/Application Support/JetBrains/IntelliJIdea2023.3/plugins/jmeter-intellij> cd lib                     PS /Users/jegors/Library/Application Support/JetBrains/IntelliJIdea2023.3/plugins/jmeter-intellij/lib> ls
ApacheJMeter_bolt.jar
ApacheJMeter_components.jar
ApacheJMeter_ftp.jar
ApacheJMeter_functions.jar
ApacheJMeter_http.jar
ApacheJMeter_java.jar
ApacheJMeter_jdbc.jar
ApacheJMeter_jms.jar
ApacheJMeter_junit.jar
ApacheJMeter_ldap.jar
ApacheJMeter_mail.jar
ApacheJMeter_mongodb.jar
ApacheJMeter_native.jar
ApacheJMeter_tcp.jar
Saxon-HE-11.5.jar
accessors-smart-2.4.11.jar
annotations-24.0.1.jar
apiguardian-api-1.1.2.jar
asm-9.3.jar
auto-common-1.2.1.jar
auto-service-1.1.0.jar
auto-service-annotations-1.1.0.jar
base-portable-jvm-3.2.0.jar
batik-anim-1.16.jar
batik-awt-util-1.16.jar
batik-bridge-1.16.jar
batik-codec-1.16.jar
batik-constants-1.16.jar
batik-css-1.16.jar
batik-dom-1.16.jar
batik-ext-1.16.jar
batik-gvt-1.16.jar
batik-i18n-1.16.jar
batik-parser-1.16.jar
batik-script-1.16.jar
batik-shared-resources-1.16.jar
batik-svg-dom-1.16.jar
batik-svggen-1.16.jar
batik-transcoder-1.16.jar
batik-util-1.16.jar
batik-xml-1.16.jar
bin
bsf-2.4.0.jar
checker-qual-3.12.0.jar
cmdrunner-2.3.jar
commons-beanutils-1.8.0.jar
commons-codec-1.15.jar
commons-collections-3.2.1.jar
commons-collections4-4.4.jar
commons-dbcp2-2.9.0.jar
commons-io-2.12.0.jar
commons-jexl-2.1.1.jar
commons-jexl3-3.2.1.jar
commons-lang-2.6.jar
commons-lang3-3.12.0.jar
commons-logging-1.2.jar
commons-math3-3.6.1.jar
commons-pool2-2.11.1.jar
commons-text-1.10.0.jar
darklaf-core-2.7.3.jar
darklaf-extensions-rsyntaxarea-0.3.4.jar
darklaf-macos-2.7.3.jar
darklaf-native-utils-2.7.3.jar
darklaf-platform-base-2.7.3.jar
darklaf-property-loader-2.7.3.jar
darklaf-theme-2.7.3.jar
darklaf-utils-2.7.3.jar
darklaf-windows-2.7.3.jar
dec-0.1.2.jar
error_prone_annotations-2.19.1.jar
ezmorph-1.0.6.jar
failureaccess-1.0.1.jar
freemarker-2.3.32.jar
geronimo-jms_1.1_spec-1.1.1.jar
guava-31.1-jre.jar
hamcrest-core-1.3.jar
hamcrest-date-2.0.8.jar
httpclient5-5.1.3.jar
httpcore5-5.1.3.jar
httpcore5-h2-5.1.3.jar
instrumented-jmeter-intellij-1.2.3.jar
j2objc-annotations-1.3.jar
javax.activation-1.2.0.jar
javax.activation-api-1.2.0.jar
jcl-over-slf4j-1.7.36.jar
jodd-core-5.0.13.jar
jodd-props-5.0.13.jar
json-lib-2.4-jdk15.jar
json-path-2.4.0.jar
json-smart-2.4.11.jar
jsr305-3.0.2.jar
jtidy-r938.jar
kotlin-logging-jvm-2.0.5.jar
kotlin-stdlib-1.7.21.jar
kotlin-stdlib-common-1.7.21.jar
kotlin-stdlib-jdk7-1.7.21.jar
kotlin-stdlib-jdk8-1.7.21.jar
kotlinx-html-jvm-0.7.3.jar
lets-plot-batik-3.2.0.jar
lets-plot-common-3.2.0.jar
listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
log4j-api-2.20.0.jar
log4j-core-2.20.0.jar
log4j-slf4j-impl-2.20.0.jar
miglayout-core-5.3.jar
miglayout-swing-5.3.jar
mxparser-1.2.2.jar
oro-2.0.8.jar
plot-api-jvm-4.4.1.jar
plot-base-portable-jvm-3.2.0.jar
plot-builder-portable-jvm-3.2.0.jar
plot-common-portable-jvm-3.2.0.jar
plot-config-portable-jvm-3.2.0.jar
rsyntaxtextarea-3.3.3.jar
serializer-2.7.3.jar
slf4j-api-1.7.36.jar
svgSalamander-1.1.2.4.jar
swing-extensions-laf-support-0.1.3.jar
swing-extensions-visual-padding-0.1.3.jar
tika-core-1.28.5.jar
vis-svg-portable-jvm-3.2.0.jar
xalan-2.7.3.jar
xercesImpl-2.12.2.jar
xml-apis-1.4.01.jar
xml-apis-ext-1.3.04.jar
xmlgraphics-commons-2.7.jar
xmlpull-1.1.3.1.jar
xmlresolver-4.6.4-data.jar
xmlresolver-4.6.4.jar
xstream-1.4.20.jar
```

**Comment by dalgarins** [comment]
@rabestro and @svenkost issue will be fixed on verison 1.2.4. next week will be available on intellij marketplace.

**Comment by dalgarins** [comment]
@rabestro and @svenkost the new version is available on marketplace, was the issue fixed to you?

**Comment by mavramopoulos** [comment]
Hello I have the same issue, running Intellij IDEA in Manjaro Linux from tar.gz. Every jmx I try to open has the same `com.thoughtworks.xstream.mapper.CannotResolveClassException: jmeterTestPlan` error. I am running latest JMeter viewer 1.2.5

**Comment by dalgarins** [comment]
@svenkost @rabestro @mavramopoulos @IncredibleLou I have rewrite the whole plugin, and I think the instability issue have been fixed: you will check the changes on version: 1.3.0

**Comment by mavramopoulos** [comment]
Hello, just tested it with latest version of Intellij IDEA Ultimate on Manjaro Linux and apache-jmeter-5.6.2, now I get this error:
`javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created`

**Comment by dalgarins** [comment]
@mavramopoulos is your file using a custom plugin?

**Comment by mavramopoulos** [comment]
@dalgarins I made it using jmeter 5.6.2 without any additional plugins, just the default tgz.

**Comment by dalgarins** [comment]
@mavramopoulos is it an empty file? Are you using plugin version 1.3.0?

**Comment by mavramopoulos** [comment]
@dalgarins The file is not empty, I've been using it with apache jmeter, I don't have plugins-manager downloaded since I have no plugins.

**Comment by dalgarins** [comment]
@mavramopoulos which plugin version are you using? I really need more information for fix the issue, first which version of the plugin are you using?

**Comment by mavramopoulos** [comment]
@dalgarins you mean the intellij plugin version? I'm using latest 1.3.0 there.

**Comment by dalgarins** [comment]
@mavramopoulos ok latest version, is it possible to you share your jmeter file?

**Comment by mavramopoulos** [comment]
[registryAuditTestForGit.jmx.tar.gz](https://github.com/anboralabs/intellij-jmeter/files/14192191/registryAuditTestForGit.jmx.tar.gz)
This is a jmeter file I used, I changed a few values because it had sensitive info.

**Comment by dalgarins** [comment]
![Screenshot 2024-02-07 at 5 22 13 AM](https://github.com/anboralabs/intellij-jmeter/assets/8527174/e09b7472-c452-4787-8a29-3432d4fabb36)

@mavramopoulos could you share the settings configuration in the ide?

<img width="971" alt="Screenshot 2024-02-06 at 6 38 40 PM" src="https://github.com/anboralabs/intellij-jmeter/assets/8527174/459f0805-53a7-4e45-84ff-b866de226e05">

**Comment by ViktorTester** [comment]
Hello, the problem occurs when I activate the plugin and try to open the .jmx file.
I have the error "The file description of toolbar icon set is not found. See logs" and infinite loading. So I need to close my IDE via task manager. But I have one way how to handle it - first I need to turn off the plugin and open all files that I need. Than I turn on the plugin and have my bug. Then I restart IDE and all files opened previously opens correctly. But its annoying. Can you help please?
![plugin_vers](https://github.com/anboralabs/intellij-jmeter/assets/93915629/bbeeaef1-e802-487b-99b4-b191a875fb8c)
![error](https://github.com/anboralabs/intellij-jmeter/assets/93915629/eaec8398-3b0b-4969-b8db-248b6eaab490)
 1.3.1

**Comment by ViktorTester** [comment]
The path to my Jmeter looks like that:
![path](https://github.com/anboralabs/intellij-jmeter/assets/93915629/bfc684cf-7e06-4b25-ad4c-fedf35a582c2)

**Comment by dalgarins** [comment]
@ViktorTester working on it, to fix it.

**Comment by dalgarins** [comment]
@ViktorTester the issue is fixed on version 1.3.3, please test it, download it from release section of this github. wait for marketplace approvel it could be longer.

**Comment by ViktorTester** [comment]
@dalgarins As I see the problem remains. First I updated the IDE Jmeter Plugin folder with 1.3.3 release, the result was same. Then  I updated my local Jmeter lib with 1.3.3 release and fail again. But let me wait for the marketplace release and I will try again. Thanks.

**Comment by dalgarins** [comment]
@ViktorTester please uninstall the plugin and install it again from marketplace, I have received the update notification right now.

**Comment by dalgarins** [comment]
@ViktorTester are you using a custom plugin in your jmx files? could you share one of your files?

**Comment by dalgarins** [comment]
@mavramopoulos the issue was fixed to you?

**Comment by dalgarins** [comment]
@ViktorTester did you have the same message about toolbar?

**Comment by ViktorTester** [comment]
Yes, I still have the same toolbar error message
and
Yes, I have custom plugins:
- JSON/YAML Plugins (deprecated)
- Markdown Table Data-driven Controller|JsonPath Assertion for sort

Here is my most common test example:
[test.zip](https://github.com/anboralabs/intellij-jmeter/files/14213297/test.zip)

**Comment by mavramopoulos** [comment]
Hello @dalgarins, I still have the same issue about selecting the jmeter home directory, I used version 1.3.3. I am getting this error:
```
cannot reset configurable

java.lang.RuntimeException: Could not read JMeter properties file:/bin/jmeter.properties
```

**Comment by dalgarins** [comment]
@ViktorTester I found the issue, it was related with custom plugins, the fix will be available on version: 1.4.0

**Comment by ViktorTester** [comment]
@dalgarins Thank you. You will release it today?

**Comment by dalgarins** [comment]
@mavramopoulos could you test version 1.4.0 on release section? let me know if that fixed your issue, if you don't want the release on marketplace.

**Comment by dalgarins** [comment]
the new version will deleted your jmeters setup before, sorry, I have to do that to fix similar issues for all people with installed previos versions.

**Comment by dalgarins** [comment]
@ViktorTester they have approved, please update and test it

**Comment by ViktorTester** [comment]
@dalgarins All works perfectly. Thanks a lot!

**Comment by ViktorTester** [comment]
@dalgarins Done. Thanks again!

**Comment by dalgarins** [comment]
@rabestro could you test the latest plugin version: 1.4.0

**Comment by rabestro** [comment]
[like]  Jegors Cemisovs reacted to your message:
________________________________

**Comment by dalgarins** [comment]
@mavramopoulos could you test again? Do you still have the issue with version: 1.4.0?

**Comment by ViktorTester** [comment]
Hello, dear @dalgarins I have multiple problems:

First - If I open my file in IDE using Jmeter plugin, and making some minor fixes in one of requests, I cannot edit all other requests, configs, controllers in this file. So I need to close the file and open again to edit something else. 
Second - when I make some changes and try to commit and push. I cant do so, because there are no changes to commit. 

Maybe Im doing something wrong, guide me please.

**Comment by dalgarins** [comment]
Hi @ViktorTester about the first issue, is fixed on version 1.4.1, please update the plugin, the plugin is this moment is only for view files not for editing sorry for that, I'm working to try to implement that.

**Comment by ViktorTester** [comment]
@ I see, yes, the first is fixed in 1.4.1. Thanks

**Comment by dalgarins** [comment]
@mavramopoulos and @rabestro is the plugin working to you?

**Comment by rabestro** [comment]
> @mavramopoulos and @rabestro is the plugin working to you?

Yes, thank you! At least it works with the build-in plugins. There was an issue with one file that uses additional plugins.

**Comment by rabestro** [comment]
> ... the plugin at this moment is only for viewing files not for editing sorry for that, I'm working to try to implement that.

This will be a great feature. 
I was confused the first time when I tried to edit the files inside JetBrains IDE using this plugin. 
Without this feature, the plugin makes little sense.

**Comment by dalgarins** [comment]
> > @mavramopoulos and @rabestro is the plugin working to you?
> 
> Yes, thank you! At least it works with the build-in plugins. There was an issue with one file that uses additional plugins. 

The plugin is working with custom plugins, could share your jmeter file with issues to validate that?

**Comment by rabestro** [comment]
> The plugin is working with custom plugins, could share your jmeter file with issues to validate that?

https://github.com/rabestro/pig-latin-rest/tree/main/jmeter-test

SmokeTest - fine
Performance - no.

```text
java.lang.IllegalArgumentException: Problem loading XML from:'/Users/jegors/Projects/engx-advanced/pig-latin-rest/jmeter-test/PerformanceTest.jmx'. 
Cause:
CannotResolveClassException: com.blazemeter.jmeter.threads.concurrency.ConcurrencyThreadGroup
```

**Comment by dalgarins** [comment]
this plugin com.blazemeter.jmeter.threads.concurrency.ConcurrencyThreadGroup is not installed in your jmeter, please install this plugin in your local jmeter, that's the reason, it show you an error. and if you have the plugin installed in you local, please make sure the jmeter settings path in intellij in the same jmeter path you have installed, and also use the latest plugin version: 1.41.

**Comment by dalgarins** [comment]
@rabestro this is my new plugin https://plugins.jetbrains.com/plugin/23812-jmeter-plugins-manager, it will allow you to detect the plugins you need for you jmeter files and will show you notifications in the IDE.

**Comment by dalgarins** [comment]
in your case will help you with the pigLatin performanceTest.

**Comment by rabestro** [comment]
[like]  Jegors Cemisovs reacted to your message:
________________________________

**Comment by dalgarins** [comment]
I think this issue is fixed. if you find another issue related, please open the reopen the issue.
